# Generated by Django 4.2.2 on 2023-07-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='num',
            field=models.IntegerField(max_length=6),
        ),
    ]
