# Generated by Django 4.2.2 on 2023-07-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='num',
            field=models.IntegerField(),
        ),
    ]
